 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var validUrl = require('valid-url');  //npm install valid-url // checks to see if URL is live
var app = express();

var mongodb = require('mongodb');
var MongoClient = mongodb.MongoClient;
var url = "mongodb://" + process.env.SECRET +"@ds149763.mlab.com:49763/freecodecamp"          ; //url for connection to database


function genShort (){
  var shortCode = [];
  var caseType;
  for (var i = 0 ; i < 6; i++){
    if (Math.floor(Math.random() * 2) === 0){
      caseType = 65; // for an uppercase letter
    } else {
      caseType = 97; //for lowercase
    }
    shortCode[i] = String.fromCharCode(Math.floor(Math.random() * 25) + caseType); // genearte number between 0 and 25 and turn it into an upper or lowercase letter
  }
  return (shortCode.join(""));
}

function addDB (short, full){
    MongoClient.connect(url, function (err, db) {
  if (err) {
    //console.log('Unable to connect to the mongoDB server. Error:', err);
  } else {
    //console.log('Connection established to', url);
    var collection = db.collection('URLS');  // seraching a collection in this docs
			
			//var doc = {				//create our document to enter shortcode and full
		//						shortcode: short
	//							,fullURl: full
	//					}
					
		    collection.insert({  //insert into our collection (docs)
				shortcode: short
								,fullURl: full
	
				},function(err, documents) { // recieve error or documents
					if (err) throw err;
					
					db.close();  // close or it get grumpy
				})
    //Close connection
  }
});  
}

function readDB (searchTerm ,searchFor, callback){
  
    MongoClient.connect(url, function (err, db) {  
      if (err) {
          //console.log('Unable to connect to the mongoDB server. Error:', err);
      } else {
          //console.log('Connection established to', url);

var collection = db.collection('URLS');  // seraching a collection in this docs
            collection.find({  //find in our collection (URL)
				         [searchTerm]:{   //need to put it in square brackets to use a variable so it knows its not a literal
					           $eq: searchFor
					        } //search for greater than or equal
				}).toArray(function(err, documents) { // recieve error or documents
              if (err) {console.log("error is" + err);}
					//console.log(documents);					
					db.close();
            callback (documents);
      }); //end of find
    }  //end of else
  })

  }


if (!process.env.DISABLE_XORIGIN) {
  app.use(function(req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/_api/package.json')
  .get(function(req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function(err, data) {
      if(err) return next(err);
      res.type('txt').send(data.toString());
    });
  });
  
app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })

// FOR all routes see if it is a valid http
app.use(function(req, res, next){
    var tempArray = (req.originalUrl).split("").slice(1);
  if (tempArray[tempArray.length-1]==="/" ) {
       tempArray =tempArray.slice(0 , -1); // remove the /
  }
    var originalURL = tempArray.join("") //read in original url remove "/"

///////////////////////////////////////////////////////// is it a valid URL that has been passed\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    if (validUrl.isUri(originalURL)) {  	// can i connect to the URL supplied? if not throw an error saves the pain of REGEX
        var urlJSON = { "original_url" : "" ,"short_url" : ""};  //make sure its blank
            // I also need to check if they have been used before so it doesnt get overwritten, highly unlikely so ive not bothered quick check is roughly a billion combos)
                urlJSON["original_url"] = originalURL;
      readDB("fullURl", originalURL, function(result){    //check to see if original url already in database. no point generating a new one. 
        if (result.length < 1){ // if result is blank then we need to generate a new one 
          var shortCode = genShort(); //generate shortcode
          addDB (shortCode , originalURL);  //add it to DB

          urlJSON["short_url"] = (req.protocol + "://" + req.get('host') + "/" + shortCode + "/");
          res.send(urlJSON);
          
        } else {  // otherwise we just pass the only shortcode back
          
          shortCode = result[0].shortcode;
          urlJSON["short_url"] = (req.protocol + "://" + req.get('host') + "/" + shortCode + "/");
          res.send(urlJSON);
        }
        
      });
      

      
      
///////////////////////////////////////////////////////// is it a shortcode?     \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    } else if (originalURL.length ===6){  // if it is 6 letters long it may be a shortcode need to check if its a shortcode
            
      readDB("shortcode", originalURL, function(result){  //look for shortcode DB and await a callback
        if (result.length < 1){  //if its not found
          var error = ('"error":"This url is not on the database."');
          res.send(error);  //if the address has not been found send error
        } else {
         res.redirect(result[0].fullURl);  //read the full url from the result and redirect it
        }
        }); //end of readb callback
      
      
///////////////////////////////////////////////////////// Not a shortURl or a proper URL throw and error\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\      
    } else {          //if  its not a valid email and its not a vailid shortcode
      var urlError = { "error":"Wrong url format, make sure you have a valid protocol and real site."};
      res.send(urlError);   
    }    
});


// Error Middleware
app.use(function(err, req, res, next) {
  if(err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }  
})

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

